AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  steeleye:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: A starter AWS Lambda function.
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::291083863193:role/service-role/lambda_basic_execution'
      Runtime: python3.6
      Timeout: 3
